In [ ]:
# data taken from: https://web.stanford.edu/class/archive/cs/cs109/cs109.1166/stuff/titanic.csv
# goal is to predict who survived (Morbid I know)
import pandas as pd
titanic_data = pd.read_csv("titanic.csv")

In [ ]:
titanic_data.head()

,Survived,Pclass,Name,Sex,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
0,0,3,Mr. Owen Harris Braund,male,22.0,1,0,7.2500
1,1,1,Mrs. John Bradley (Florence Briggs Thayer) Cum...,female,38.0,1,0,71.2833
2,1,3,Miss. Laina Heikkinen,female,26.0,0,0,7.9250
3,1,1,Mrs. Jacques Heath (Lily May Peel) Futrelle,female,35.0,1,0,53.1000
4,0,3,Mr. William Henry Allen,male,35.0,0,0,8.0500

In [ ]:
# The goal is to find out who survived
# find whats wrong with data
# lets use the decribe function (critocal for understanding)
titanic_data.describe()

,Survived,Pclass,Age,Siblings/Spouses Aboard,Parents/Children Aboard,Fare
count,887.000000,887.000000,887.000000,887.000000,887.000000,887.00000
mean,0.385569,2.305524,29.471443,0.525366,0.383315,32.30542
std,0.487004,0.836662,14.121908,1.104669,0.807466,49.78204
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.00000
25%,0.000000,2.000000,20.250000,0.000000,0.000000,7.92500
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.45420
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.13750
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.32920

In [ ]:
# lets try look at the data another way
# we dont have all feautures
titanic_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 887 entries, 0 to 886
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Survived                 887 non-null    int64
 1   Pclass                   887 non-null    int64
 2   Name                     887 non-null    object
 3   Sex                      887 non-null    object
 4   Age                      887 non-null    float64
 5   Siblings/Spouses Aboard  887 non-null    int64
 6   Parents/Children Aboard  887 non-null    int64
 7   Fare                     887 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 55.6+ KB

In [ ]:
# issue 1 is null values / missing values
# issue 2 is multiple feautures of information in one column
# issue 3 data typles in intergera, floats and objects
titanic_data["Name"].sample(25)

15                  Mrs. (Mary D Kingcome) Hewlett
35                   Mr. Alexander Oskar Holverson
845    Mrs. Samuel L (Edwiga Grabowska) Goldenberg
791                              Mr. Richard Otter
458                             Mr. William Morley
546                  Master. John Morgan Jr Davies
566                               Mr. Carl Jonsson
115                            Mr. Patrick Connors
600                       Mr. Ernst William Torber
146                       Miss. Robina Maggie Ford
358                              Mr. Wilhelm Skoog
243                            Mr. Sleiman Attalah
674                         Miss. Anna Sofia Turja
65                     Mrs. (Elizabeth Ramell) Nye
406               Mr. Hans Martin Monsen Birkeland
464                      Mr. John Montgomery Smart
155                        Miss. Katherine Gilnagh
78                         Miss. Elizabeth Dowdell
762                       Dr. Arthur Jackson Brewe
138                              Mr. Victor Giglio
691                                 Col. John Weir
136                     Mr. Jacques Heath Futrelle
556    Mrs. Guillaume Joseph (Emma) de Messemaeker
745                         Mr. Michael Connaghton
708                              Mr. Herman Klaber
Name: Name, dtype: object

In [ ]:
 # data collection not clean. How long last name (indication of class), title (indicating social class) and gender
# issue 3 , alot of noisy data:
titanic_data["Siblings/Spouses Aboard"].sample(25)

579    0
369    1
195    0
703    0
730    0
229    1
741    1
179    8
831    1
808    0
585    0
83     0
417    0
536    0
694    0
810    0
735    0
470    0
817    0
577    1
441    0
211    0
560    0
199    0
54     0
Name: Siblings/Spouses Aboard, dtype: int64

In [ ]:
titanic_data["Parents/Children Aboard"].sample(25)

843    0
664    0
362    0
680    2
278    0
759    2
672    0
88     0
123    1
388    2
600    0
692    0
838    0
24     1
697    0
14     0
563    0
55     0
179    2
860    0
513    0
675    6
543    0
698    0
426    0
Name: Parents/Children Aboard, dtype: int64

In [14]:
# discard a feautures or imporove to prevent affecting numbers
# How to choose a Model:
# What does each model do? How does model work?
# Try diffrent models on data, test which gives the best result
# Models Assumptions: what can model learn and what does data look like ?
# Assess model performance using metrics like accuracy, precision, recall etc
# Hyper parameters: what variations of the model do we use?
# parameters: fitted and learned "knowledge"
# information from api reference of sklearn

In [3]:
# linear model:
# linear models captures linear relationships between features and the response
# In what what way do we want our linear model to learn the linear relationship
# whats the co-efficient of particular feature

In [2]:
# Clustering Models:
# don't require a targets, organizing similar things together
# Unsupervised learning on design matrix
# looks how close or far things are from each other to decide which ones belong together in the same group

In [1]:
# Ensemble methods
# for classification, reggression, and anomaly detection
# Put multiple models together and "vote" on final outcome
# power of diffrent models

In [5]:
# Gaussian Processes
# bassed on reggression and classification
# assumes for each data point there is a gaussian distribution around that data points
# uses gaussian distributions to formulate where the fitted line should be

In [6]:
# Gaussian Mixture models
# implements mixture modeling algorithims
# model distributions with a combination of gausian distributions

In [12]:
# Naive Beyes
# supervised learning models
# assumes that each feature is independant/ unrelated of other features
# calculates the probabilty of something being a certain type based on how often that type appears with certain features
# Uses Bayes'theorum to find out importance of each feature to the reponse

In [16]:
# Nearest Neighbors
# creates a prediction by looking at what are the nearest data points to the data point we are tryiing to predict
# using the majority labels of thier neighbors as the prediction

In [9]:
# Neural Network Models
# based on nural networks of the brain
# Classifer and regression models

In [13]:
# Support Vector Machines
# finds the best to seperate groups
# uses support vector alogrithims

In [11]:
# Decision trees
# split data according to crteria then within each spilt we further split with another critera
# models for classification and regression